spring.application.name=GhbliAPI

stability.api.base-url=https://api.stability.ai

stability.api.key=${STABILITY_API_KEY}

# Fein client configuration to handle multipart / form-data requests
fein.encode.encoder-class=org.spingframework.openfeign.support.SpringEncoder

# Allow larger image uploads (default is 1MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB